# Generated by Django 4.1 on 2023-06-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloggg',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=15)),
                ('img', models.FileField(default='', upload_to='')),
                ('cat', models.CharField(max_length=15)),
                ('summ', models.TextField(max_length=50)),
                ('con', models.TextField(max_length=1000)),
            ],
        ),
    ]
