# Generated by Django 4.1 on 2023-06-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bloggg_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggg',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
